DROP TABLE MEMBER;
CREATE TABLE MEMBER (
    MID NVARCHAR2(15) CONSTRAINT PK_MEM PRIMARY KEY,
    MPW NVARCHAR2(15) NOT NULL,
    MNAME NVARCHAR2(5) NOT NULL,
    MBIRTH DATE NOT NULL,
    MPHONE NVARCHAR2(15) NOT NULL,
    MEMAIL NVARCHAR2(30) NOT NULL,
    MADDRESS NVARCHAR2(50) NOT NULL,
    MPROFILE NVARCHAR2(50));


DROP TABLE BLOG;
CREATE TABLE BLOG (
    BLOGNUM NUMBER(2) CONSTRAINT PK_BLOG PRIMARY KEY,
    BLOGID NVARCHAR2(15) CONSTRAINT FK_BLOG REFERENCES MEMBER(MID),
    BLOGNAME NVARCHAR2(20) NOT NULL,
    BLOGIMAGE NVARCHAR2(50),
    BLOGHITS NUMBER(3));
DROP SEQUENCE SEQ_BLOG;
CREATE SEQUENCE SEQ_BLOG
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE;


DROP TABLE BOARD;
CREATE TABLE BOARD(
    BNUMBER NUMBER(2) CONSTRAINT PK_BOARD PRIMARY KEY,
    BWRITER NVARCHAR2(15) CONSTRAINT FK_BOARD REFERENCES MEMBER(MID),
    BTITLE NVARCHAR2(30) NOT NULL,
    BCONTENTS NVARCHAR2(50) NOT NULL,
    BDATE DATE NOT NULL,
    BHITS NUMBER(3),
    BFILE NVARCHAR2(50),
    BCATEGORY NVARCHAR2(10));
DROP SEQUENCE SEQ_BOARD;
CREATE SEQUENCE SEQ_BOARD
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE;

DROP TABLE CATEGORY;
CREATE TABLE CATEGORY(
    CNUMBER NUMBER(2) CONSTRAINT PK_CATEGORY PRIMARY KEY,
    CWRITER NVARCHAR2(15) CONSTRAINT FK_CATEGORY REFERENCES MEMBER(MID),
    CNAME NVARCHAR2(30) NOT NULL);
DROP SEQUENCE SEQ_C;
CREATE SEQUENCE SEQ_C
    START WITH 1 
    INCREMENT BY 1 
    NOCACHE;

CREATE VIEW BOARDLIST AS SELECT B.*, ROW_NUMBER() OVER(ORDER BY BNUMBER DESC) AS RN FROM BOARD B;